version: '3'
services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:alpine'
  nginx:
    restart: always
    depends_on:
      - api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379